[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "https://modovate-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
