[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[headers]]
  for = "/api-proxy/*"
  [headers.values]
    Cache-Control = "no-store"

[[redirects]]
  from = "/api-proxy/*"
  to = "https://modovate-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://modovatestudio.com/*"
  to = "https://www.modovatestudio.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
